#
# Copyright 2015-2019 VMware, Inc. All Rights Reserved.
# Author: Tom Hite (thite@vmware.com)
#
# SPDX-License-Identifier: https://spdx.org/licenses/MIT.html
#

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: go-reminders
  labels:
    app: go-reminders
spec:
  selector:
    matchLabels:
      app: go-reminders
  template:
    metadata:
      labels:
        app: go-reminders
    spec:
      containers:
        - name: go-reminders
          image: {{docker-registry-repo}}
          command:
            - "/go-reminders"
            - "-dbtype=mem"
          ports:
            - containerPort: 8080
              name: go-reminders
              protocol: TCP
      imagePullSecrets:
        - name: go-reminders-registry-creds
